### PR TITLE
styled the sign in Button

### PR DESCRIPTION
**Pull request by KlausMikhaelson**
Hey, I have just added that in the sign in button for now just so that you can see and let me know if it's good or not, if not than will change it a big and I added "Login with Google" instead of "Sign in", let me know if it's okay to make it like this so that I can change the sign out button as well or else I can even try something else

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Hey @KlausMikhaelson, thanks for the PR!

The new button looks good but I think it can be better, first off the `box-shadow` can be made softer and as we are using a google icon already I don't think there's a need for the full phrase `Log in with Google` just `Log in` is acceptable.

**Comment by KlausMikhaelson** [comment]
Okay @Dharmik48 will make those changes

**Comment by KlausMikhaelson** [comment]
Hey @Dharmik48 I have made those changes but I wasn't able to check the changes for the sign out button since it was collapsing again and again even before being able to sign in so I know it's a firebase ac issue but it should be working with the official one so can you review it now ?

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Now it looks better🚀

The login error was because the `config.js` file was changed and it couldn't connect to firebase, but I added the original config, and now it's working!

Just one thing, can you revert the `package-lock.json` file? As we are not supposed to change that. So just revert it back and we'll merge the PR🚀

**Comment by KlausMikhaelson** [comment]
Hi @Dharmik48 ig I changed that file with the one in the main branch so it should be good to merge now ig

**Review by Dharmik48 — COMMENTED** [review]
LGTM🚀

Great work @KlausMikhaelson! Thanks a lot for contributing😊

**Pull request merged**
