### PR TITLE
Styled Sign In Button with no changes to package-lock.json

### PR DESCRIPTION
**Pull request by bhavya-giri**

### CODE REVIEW

**Review by Dharmik48 — APPROVED** [review]
LGTM🚀

Looks great! Thanks a lot for contributing😊

**Comment by bhavya-giri** [comment]
Anytime buddy, would love to contribute more.
Let's exchange notes someday?

**Comment by Dharmik48** [comment]
> Let's exchange notes someday?

What exactly do you mean by notes?

**Comment by bhavya-giri** [comment]
like have a meet or something, what's your twitter handle?

**Comment by Dharmik48** [comment]
It is [@frontendilia](https://twitter.com/frontendilia)

**Pull request merged**
