### PR TITLE
Updated the Readme.md file.

### PR DESCRIPTION
**Pull request by SalmanShahid888**

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Great work @SalmanShahid888 🎉

Can you also add a `Thanks to all contributors` section like in [this repo](https://github.com/Dharmik48/quizzical#thanks-to-all-contributors)?

And also please don't edit the `package-lock.json` file, please revert the changes in the file

**Comment by SalmanShahid888** [comment]
I have added a contribution section to README.md file and reverted the package-lock.json

**Review by Dharmik48 — APPROVED** [review]
This looks great!🚀

One last thing, can you also add screenshots of the website too?

**Comment by SalmanShahid888** [comment]
Updated Readme.md with screenshots

**Review by Dharmik48 — APPROVED** [review]
Great work🚀

It looks good to merge! Thanks a lot for contributing 😊

**Pull request merged**
